server:
  port: 4001

spring:
  application:
    name: vcloud-config-server
  profiles:
    active: dev
  cloud:
    config:
      server:
        git:
          uri: http://192.168.199.239/root/v-cloud-config.git
          username: root
          password: pwl123456789

---
spring:
  profiles: dev
eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5 #表示eureka client发送心跳给server端的频率
    lease-expiration-duration-in-seconds: 20 #leaseExpirationDurationInSeconds后，server端没有收到client的心跳，则将摘除该instance
  client:
    serviceUrl:
      defaultZone: http://root:root@127.0.0.1:1025/eureka/  #eureka 注册地址
    registry-fetch-interval-seconds: 10  #表示eureka client间隔多久秒去拉取服务注册信息
